### PR TITLE
docs(api): updates documentation

### PR DESCRIPTION
**Pull request by cowwoc**
My attempt at clarifying the documentation.

### CODE REVIEW

**Comment by mdreizin** [comment]
@cowwoc It is ok, but api doc is auto-generated and you need to modify files under `.gitdown/docs/API.md`.

**Comment by cowwoc** [comment]
@mdreizin Try now.

**Comment by mdreizin** [comment]
@cowwoc Awesome, but need to update `watch` section too.

**Comment by cowwoc** [comment]
@mdreizin What do you mean about needing to update the `watch` section? Also, you closed this issue... does that mean you fixed the `watch` section yourself?

**Comment by mdreizin** [comment]
@cowwoc The `watch` section also has `useMemoryFs` option and it should be updated too. I have merged this PR and applied these changes by myself. Thanks a lot ;)

**Pull request merged**
